### ISSUE TITLE
Dashboard not loading

### ISSUE THREAD

**Issue by Rumpfinger** [expertasolutions/VstsDashboard#133]
For one of our project, dashboard is not loading and we get just an empty page.
attached the console log of Chrome browser

[tfs.euip.devcerner.net-1591956909953.log](https://github.com/expertasolutions/VstsDashboard/files/4770179/tfs.euip.devcerner.net-1591956909953.log)

**Comment by lturmel** [comment]
Hi @Rumpfinger,

Thanks for the bug report. I'm quite busy, but I will do my best to fix this soon, and let you know it's ready.

thanks again,
