### ISSUE TITLE
Create default settings for Status Order and TeamProjects global filters

### ISSUE THREAD

**Issue by rkenshin** [expertasolutions/VstsDashboard#137]
Change the order status sorting to sort by default by Queue Date

**Comment by lturmel** [comment]
This goes contrary to the issue #83 that were previously requested from another users.

To make the life easier for everyone around this, I will add an organization settings where it will be possible to set the default preference for this extensions.

**Comment by lturmel** [comment]
After a review base from the issue #141, I will save the last selected status order into a "User preference" extension data.
When users will go back on the dashboard, it will load theirs latest filter options by default.
This is already implemented for the "Projects List" dropdown (into the Issue0141 branch)

**Comment by lturmel** [comment]
Completed from the PR #143

**Comment by lturmel** [comment]
@rkenshin  It's now deployed, make sure you accept the extension permission in your organization settings
