### ISSUE TITLE
Add committer name next to change set number

### ISSUE THREAD

**Issue by rkenshin** [expertasolutions/VstsDashboard#138]
Add committer name next to the change set number in Build# column

**Comment by lturmel** [comment]
Unfortunately I decide to not add this information into the dashboard. The purpose of the dashboard is to follow the flow of the build/release status base from "who" start/trigger the build. I understand that we could want to know "who" commit/checkin code changes that can affect the build status. That information can be found easily from the "commit"/"changeset" link present under the "Build# | Branch & Commit" columns.
