### ISSUE TITLE
How to save dashboard research parameters ?

### ISSUE THREAD

**Issue by cyrilen** [expertasolutions/VstsDashboard#139]
Hi,

Every time I come back to the CI/CD dashboard I have to tweak it to display everything I want and would like to save that to be default every time I open it. How can I achieve that ?

Thank you.

**Comment by lturmel** [comment]
Hi @cyrilen, I will need to put do work to make it happen, because I like the idea to have some saved filters criteria.

**Comment by lturmel** [comment]
Hi @cyrilen , since you open this issue, I've completed the save of UserPreference filter from the issue #141 and #137.
The only filter parameters that isn't yet save is the Keyword filter. I'm looking to be able to save this keyword filters in order to keep an history of it.

**Comment by lturmel** [comment]
Hi @cyrilen , since you open this issue, I've completed the save of UserPreference filter from the issue #141 and #137.
This delivery of these two issue will be avail in the next release define from the milestone [Release-August-2020](https://github.com/expertasolutions/VstsDashboard/milestone/5)

**Comment by lturmel** [comment]
@cyrilen It's now deployed, make sure you accept the extension permission in your organization settings

**Comment by cyrilen** [comment]
Working great, thanks.
