### ISSUE TITLE
Sticky Selected Projects Filter

### ISSUE THREAD

**Issue by tbconrad** [expertasolutions/VstsDashboard#141]
Would it be possible to have the filter remember the selected projects? We use a "General" project for PBI, Tasks ect so it would be nice if I could run the CI/CD monitor from that General project and retain the CI/CD projects that I select selected without have to re-select them each time I open the dashboard.

**Comment by lturmel** [comment]
Hi @tbconrad, yes, I will try to find time to make it happen in order to deliver it with this milestone [Release-August-2020](https://github.com/expertasolutions/VstsDashboard/milestone/5)

**Comment by lturmel** [comment]
Hi @tbconrad , the change has been made and it's ready for next delivery once the milestone is completed.

**Comment by tbconrad** [comment]
Thanks, I just had a chance to check it out. It works great.

**Comment by lturmel** [comment]
> Thanks, I just had a chance to check it out. It works great.

Thanks, I've just fix a little issue this morning... first load was crashing... :0(
Now it's fixed..
Thanks for your suggestion btw
