### ISSUE TITLE
Enable extension for certain role or project only

### ISSUE THREAD

**Issue by sanjeev40084** [expertasolutions/VstsDashboard#87]
Currently once the extension is installed, it is available for all projects and everyone can view it. It  would nice to only make this extension available for user with certain role (like: Global Administrator) or certain projects only.

**Comment by lturmel** [comment]
Thank you for your request and comment. Currently theirs no plan to add this kind of capability. 

The purpose of that extension is simply to easily follow Builds and Release from a merged view.

Right now the projects accessible from the list is based on the users project permissions.
Users that can access to Team Project "A", will be able to pick-n-choose from the Team Project dropdown filter. If not, the Team project will not be displayed in that list.
