### ISSUE TITLE
Exceeding rate limiting thresholds

### ISSUE THREAD

**Issue by dhack-dxc** [expertasolutions/VstsDashboard#93]
After installing this add-on (great add-on btw), we started getting warnings from DevOps that our usage had exceeded rate limiting thresholds and DevOps became very slow.

We have a fairly large project with approximately 60 build pipelines, and 20-50 releases per build.

Could the add-on be optimised for large use case scenarios such as ours?

**Comment by lturmel** [comment]
Hi @dhack-dxc , I understand very well the problems, of course I can optimized how I pull the data from AzureDevOps API. With the Covid19 situation, I'm less busy than normally, so I will start working on this optimization this friday.

Thanks for the feedback !

**Comment by lturmel** [comment]
Quick Update: @dhack-dxc I've been able to reduced the TSTUs usage by 10 when times come to pull Builds info.

I've also put some limitation about the "All Runs" view, where it will be possible to list builds from this time range:

- Last hour (by default)
- Last 4 hours
- Last 8 hours
- Yesterday
- Last Week

Will do some extensive tests to ensure it's ok, before pushing it on the marketplace. For sure, it should be better than before.

**Comment by lturmel** [comment]
> After installing this add-on (great add-on btw), we started getting warnings from DevOps that our usage had exceeded rate limiting thresholds and DevOps became very slow.
> 
> We have a fairly large project with approximately 60 build pipelines, and 20-50 releases per build.
> 
> Could the add-on be optimised for large use case scenarios such as ours?

I've just publish the [v1.20095.33](https://marketplace.visualstudio.com/items?itemName=experta.cicd-dashboard), which include optimized API call to Azure DevOps to limit the TSTUs usage. 

I will wait your input regarding this issue, to know if it's better or not from you side, regarding your large scale scenario.

If not, I invite you to give more details about, like:
- Number of build per days (average)
- Number of release per days (average)

thanks,

**Comment by dhack-dxc** [comment]
Thanks @lturmel, we'll try out the new version and let you know how it goes.

**Comment by lturmel** [comment]
> Thanks @lturmel, we'll try out the new version and let you know how it goes.

I've spotted another pain point, yesterday from my customer Azure DevOps Server instance, so I will also continue to made improvement for that optimization subject. Working remotely is quite different than working on-site.

**Comment by lturmel** [comment]
> Thanks @lturmel, we'll try out the new version and let you know how it goes.

I've just release [v1.20100.36](https://github.com/expertasolutions/VstsDashboard/releases/tag/1.20100.36), with other improvement around this.

**Comment by dhack-dxc** [comment]
Can confirm it's performing much better and DevOps is no longer reporting "Exceeding rate limiting thresholds".

Feel free to close this issue if you wish.

**Comment by lturmel** [comment]
Thanks @dhack-dxc for the confirmation that it’s resolving your issue.
