### ISSUE TITLE
Add Release Notes in Azure DevOps Marketplace

### ISSUE THREAD

**Issue by sanjeev40084** [expertasolutions/VstsDashboard#96]
Since there is constant release of this extension it would be nice to have some release notes in DevOps marketplace.

**Comment by lturmel** [comment]
Thanks for asking. It's definitely something planned, but not prioritized wet...

**Comment by lturmel** [comment]
@sanjeev40084 I've take the time to make release note automatically release from my pipeline via the GitHub release feature. The release notes will be avail from the marketplace extension page and the v1.x.y link on the main extension page. Thanks again ;)

**Comment by sanjeev40084** [comment]
Highly appreciated 🙏
